### ISSUE TITLE
[enhancement] Ensure 'typos' list can't contain the actual name of the element

### ISSUE THREAD

**Issue by matirko** [greystorm101/spritebot#12]
For example
```
    },
	    {
        "id": "450_1",
        "name": "ultranecrozma",
        "typos": ["ultra", "necrozmaultra", "ultranecrosma"],
        "display_name": "Ultra Necrozma"
    },
 ```
    
    
    
If the `typos` list contained a typo that was unintentionally the same as name, this would likely break things. Should we validate the typos list at startup?

**Comment by greystorm101** [comment]
It should be ok if there are duplicates actually, it just makes a disctionary that maps names to ids like this:
```
{'bulbasaur': '1', 'bulbosaur': '1', 'bulbusaur': '1', 'bulbassauro': '1', 'ivysaur': '2', 'ivyssauro': '2', 'venusaur': '3', 'venasaur': '3', 'venussauro': '3', 'charmander': '4
```
If a python dict has duplicate keys, it just ignores duplicates (just tested locally)

That said, I would like to get some unit tests stood up here
